// AUTO-GENERATED by scripts/build-varieties.ts — do not edit by hand.
// Edit the source files in content/varieties/*.md, then run `pnpm varieties:build`.
import type { Variety } from "./types";

export const VARIETIES: Variety[] = [
  {
    "slug": "tulip",
    "name": "Specialty Tulips",
    "botanical": "Tulipa — doubles, parrots, fringed",
    "category": "focal",
    "availableFromWeek": 14,
    "availableToWeek": 18,
    "availableForContract": true,
    "notes": "Field-grown doubles and parrots the box-lot importers never carry. Cut in bud, ship stiff, open in the cooler. First color of the season."
  },
  {
    "slug": "anemone",
    "name": "Anemone",
    "botanical": "Anemone coronaria",
    "category": "focal",
    "availableFromWeek": 15,
    "availableToWeek": 21,
    "availableForContract": true,
    "notes": "Saturated jewel tones with a dark center. Cool-season bloomer; volume tapers as nights warm. Substitutes cleanly for ranunculus in early designs."
  },
  {
    "slug": "ranunculus",
    "name": "Ranunculus",
    "botanical": "Ranunculus asiaticus — Amandine & Elegance",
    "category": "focal",
    "availableFromWeek": 16,
    "availableToWeek": 22,
    "availableForContract": true,
    "notes": "Dozens of tissue-thin petals, long vase life. The signature spring focal. Order early — contract rows sell out first."
  },
  {
    "slug": "peony",
    "name": "Peony",
    "botanical": "Paeonia lactiflora",
    "category": "focal",
    "availableFromWeek": 20,
    "availableToWeek": 24,
    "availableForContract": true,
    "notes": "A tight three-week window that every couple wants. Cut at marshmallow-soft bud, store dry. Reserve a season ahead — supply is fixed by the field."
  },
  {
    "slug": "snapdragon",
    "name": "Snapdragon",
    "botanical": "Antirrhinum majus — Chantilly & Madame Butterfly",
    "category": "spike",
    "availableFromWeek": 20,
    "availableToWeek": 40,
    "availableForContract": true,
    "notes": "Dependable vertical line all season with successional sowings. Open-faced Chantilly types for airy work, doubles for weight."
  },
  {
    "slug": "sweet-pea",
    "name": "Sweet Pea",
    "botanical": "Lathyrus odoratus",
    "category": "specialty",
    "availableFromWeek": 20,
    "availableToWeek": 26,
    "availableForContract": false,
    "notes": "True scent, ruffled wings — and a two-day ship life that keeps them off the import trucks. Local-only by nature. Pickup or same-day delivery."
  },
  {
    "slug": "eucalyptus",
    "name": "Eucalyptus & Cut Foliage",
    "botanical": "Eucalyptus, basil, mint, scented geranium",
    "category": "foliage",
    "availableFromWeek": 22,
    "availableToWeek": 44,
    "availableForContract": true,
    "notes": "The greenery that ties an arrangement together, cut fresh instead of gassed and boxed. Steady supply from late spring through frost."
  },
  {
    "slug": "ammi",
    "name": "Ammi (False Queen Anne's Lace)",
    "botanical": "Ammi majus",
    "category": "filler",
    "availableFromWeek": 24,
    "availableToWeek": 34,
    "availableForContract": true,
    "notes": "Lacy white umbels that give designs air without weight. The workhorse filler from early summer through late August."
  },
  {
    "slug": "cosmos",
    "name": "Cosmos",
    "botanical": "Cosmos bipinnatus — Double Click & Cupcakes",
    "category": "filler",
    "availableFromWeek": 26,
    "availableToWeek": 42,
    "availableForContract": true,
    "notes": "Fluttery movement and doubles that photograph beautifully. Delicate to ship long-haul, so a natural fit for local weekly delivery."
  },
  {
    "slug": "sunflower",
    "name": "Sunflower",
    "botanical": "Helianthus annuus — pollenless ProCut",
    "category": "focal",
    "availableFromWeek": 26,
    "availableToWeek": 42,
    "availableForContract": true,
    "notes": "Pollenless, single-stem, cut at first color. Cheerful volume for markets and corporate work. Successional blocks keep them coming weekly."
  },
  {
    "slug": "zinnia",
    "name": "Zinnia",
    "botanical": "Zinnia elegans — Benary's Giant & Oklahoma",
    "category": "filler",
    "availableFromWeek": 26,
    "availableToWeek": 42,
    "availableForContract": true,
    "notes": "High-summer color by the bucket. Cut hard (the \"wiggle test\") for a full week in the vase. The backbone of market bouquets."
  },
  {
    "slug": "celosia",
    "name": "Celosia",
    "botanical": "Celosia argentea — cristata & plumosa",
    "category": "focal",
    "availableFromWeek": 28,
    "availableToWeek": 42,
    "availableForContract": true,
    "notes": "Velvety brains and plumes in scorched, on-trend tones. Loves the heat, holds for weeks fresh, and dries for everlasting work."
  },
  {
    "slug": "lisianthus",
    "name": "Lisianthus",
    "botanical": "Eustoma grandiflorum",
    "category": "focal",
    "availableFromWeek": 28,
    "availableToWeek": 40,
    "availableForContract": true,
    "notes": "Rose-like ruffles, two-week vase life, no thorns. A premium focal that reads bridal. Long to grow, so contract quantities are set in winter."
  },
  {
    "slug": "dahlia",
    "name": "Dahlia",
    "botanical": "Dahlia — dinnerplate, ball & cactus",
    "category": "focal",
    "availableFromWeek": 30,
    "availableToWeek": 44,
    "availableForContract": true,
    "notes": "The late-season headliner: dinnerplates to pompons in every tone. Zero ship life — dahlias are local-florist gold. Contract rows planted to your palette."
  }
];
