/**
 * Compiles the Knowledge Base.
 *
 * Reads every `content/knowledge/*.md` file (YAML front-matter + markdown body),
 * validates the front-matter, renders the body to HTML, and emits a single typed
 * module at `lib/knowledge/generated.ts`. The app imports that module directly, so
 * the whole library ships in the JS bundle and is fully available offline — no
 * runtime markdown parsing, no network, no DB.
 *
 * Run with: `pnpm knowledge:build`
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { marked } from "marked";
import { z } from "zod";

const CONTENT_DIR = join(process.cwd(), "content", "knowledge");
const OUT_FILE = join(process.cwd(), "lib", "knowledge", "generated.ts");

const stepSchema = z.object({ icon: z.string(), text: z.string() });
const ingredientSchema = z.object({
  item: z.string(),
  qty: z.union([z.string(), z.number()]).optional(),
  unit: z.string().optional(),
});

const frontMatterSchema = z.object({
  id: z.string(),
  title: z.string(),
  abbr: z.string().optional(),
  source: z.enum(["KNF", "MM", "SoilLandFood"]),
  category: z.enum([
    "microbial-culture",
    "plant-ferment",
    "fruit-ferment",
    "mineral-extract",
    "amino-acid",
    "liquid-fertilizer",
    "solid-fertilizer",
    "pest-control",
    "biostimulant",
    "concept",
    "application",
  ]),
  stage: z.array(z.enum(["vegetative", "cross-over", "reproductive", "all-stages", "soil"])),
  supplies: z.array(z.string()).default([]),
  difficulty: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  time_days: z.tuple([z.number(), z.number()]).nullable().default(null),
  dilution: z.string().optional(),
  summary: z.string(),
  ferment_type: z.string().optional(),
  ingredients: z.array(ingredientSchema).default([]),
  steps: z.array(stepSchema).default([]),
  tags: z.array(z.string()).default([]),
  related: z.array(z.string()).default([]),
});

marked.setOptions({ gfm: true, breaks: false });

function buildSearchText(fm: z.infer<typeof frontMatterSchema>, body: string): string {
  return [
    fm.title,
    fm.abbr ?? "",
    fm.summary,
    fm.supplies.join(" "),
    fm.tags.join(" "),
    fm.ingredients.map((i) => i.item).join(" "),
    body.replace(/[#>*`_\-]/g, " "),
  ]
    .join(" ")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function main() {
  const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));
  if (files.length === 0) throw new Error(`No .md files found in ${CONTENT_DIR}`);

  const docs = files
    .map((file) => {
      const raw = readFileSync(join(CONTENT_DIR, file), "utf8");
      const { data, content } = matter(raw);
      const parsed = frontMatterSchema.safeParse(data);
      if (!parsed.success) {
        throw new Error(`Invalid front-matter in ${file}:\n${JSON.stringify(parsed.error.format(), null, 2)}`);
      }
      const fm = parsed.data;
      const bodyHtml = marked.parse(content.trim()) as string;
      return {
        id: fm.id,
        title: fm.title,
        abbr: fm.abbr,
        source: fm.source,
        category: fm.category,
        stage: fm.stage,
        supplies: fm.supplies,
        difficulty: fm.difficulty,
        timeDays: fm.time_days,
        dilution: fm.dilution,
        summary: fm.summary,
        fermentType: fm.ferment_type,
        ingredients: fm.ingredients.map((i) => ({ ...i, qty: i.qty == null ? undefined : String(i.qty) })),
        steps: fm.steps,
        tags: fm.tags,
        related: fm.related,
        bodyHtml,
        searchText: buildSearchText(fm, content),
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));

  const ids = new Set<string>();
  for (const d of docs) {
    if (ids.has(d.id)) throw new Error(`Duplicate knowledge id: ${d.id}`);
    ids.add(d.id);
  }

  const header =
    "// AUTO-GENERATED by scripts/build-knowledge.ts — do not edit by hand.\n" +
    "// Edit the source files in content/knowledge/*.md, then run `pnpm knowledge:build`.\n" +
    'import type { KnowledgeDoc } from "./types";\n\n';
  const body = `export const KNOWLEDGE_DOCS: KnowledgeDoc[] = ${JSON.stringify(docs, null, 2)};\n`;

  writeFileSync(OUT_FILE, header + body, "utf8");
  console.log(`Knowledge base built: ${docs.length} docs → ${OUT_FILE}`);
}

main();
