/**
 * Compiles the Variety collection (the farm's seasonal crop list).
 *
 * Reads every `content/varieties/*.md` file (YAML front-matter; the markdown
 * body, if any, is used as the trade note), validates it, and emits a single
 * typed module at `lib/varieties/generated.ts`. The seasonal availability chart
 * on `/florists` imports that module directly — no runtime CMS, no network.
 *
 * Authoring workflow: add/edit a `.md` in `content/varieties/`, then run
 * `pnpm varieties:build` (also runs automatically on `build`). Set
 * `draft: true` to keep a variety in the repo without shipping it.
 *
 * Run with: `pnpm varieties:build`
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { z } from "zod";

const CONTENT_DIR = join(process.cwd(), "content", "varieties");
const OUT_FILE = join(process.cwd(), "lib", "varieties", "generated.ts");

const week = z.coerce.number().int().min(1).max(53);

const frontMatterSchema = z
  .object({
    slug: z.string().regex(/^[a-z0-9-]+$/, "slug must be kebab-case (a-z, 0-9, -)"),
    name: z.string().min(1),
    botanical: z.string().optional(),
    category: z.enum(["focal", "spike", "filler", "foliage", "specialty"]),
    availableFromWeek: week,
    availableToWeek: week,
    availableForContract: z.boolean().default(false),
    notes: z.string().optional(),
    photo: z.string().optional(),
    draft: z.boolean().default(false),
  })
  .refine((v) => v.availableToWeek >= v.availableFromWeek, {
    message: "availableToWeek must be >= availableFromWeek",
    path: ["availableToWeek"],
  });

function main() {
  const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));
  if (files.length === 0) throw new Error(`No .md files found in ${CONTENT_DIR}`);

  let skipped = 0;
  const varieties = files
    .map((file) => {
      const raw = readFileSync(join(CONTENT_DIR, file), "utf8");
      const { data, content } = matter(raw);
      const parsed = frontMatterSchema.safeParse(data);
      if (!parsed.success) {
        throw new Error(
          `Invalid front-matter in ${file}:\n${JSON.stringify(parsed.error.format(), null, 2)}`,
        );
      }
      const fm = parsed.data;
      if (fm.draft) {
        skipped++;
        return null;
      }
      const body = content.trim();
      return {
        slug: fm.slug,
        name: fm.name,
        botanical: fm.botanical,
        category: fm.category,
        availableFromWeek: fm.availableFromWeek,
        availableToWeek: fm.availableToWeek,
        availableForContract: fm.availableForContract,
        // Prefer the front-matter note; fall back to the markdown body.
        notes: fm.notes ?? (body.length > 0 ? body : undefined),
        photo: fm.photo,
      };
    })
    .filter((v): v is NonNullable<typeof v> => v !== null)
    // Sort by first-available week, then name — reads top-to-bottom as the
    // season opens, which is how the chart wants its rows.
    .sort((a, b) =>
      a.availableFromWeek !== b.availableFromWeek
        ? a.availableFromWeek - b.availableFromWeek
        : a.name.localeCompare(b.name),
    );

  if (varieties.length === 0) {
    throw new Error(`Every variety in ${CONTENT_DIR} is a draft — nothing to publish.`);
  }

  const slugs = new Set<string>();
  for (const v of varieties) {
    if (slugs.has(v.slug)) throw new Error(`Duplicate variety slug: ${v.slug}`);
    slugs.add(v.slug);
  }

  const header =
    "// AUTO-GENERATED by scripts/build-varieties.ts — do not edit by hand.\n" +
    "// Edit the source files in content/varieties/*.md, then run `pnpm varieties:build`.\n" +
    'import type { Variety } from "./types";\n\n';
  const body = `export const VARIETIES: Variety[] = ${JSON.stringify(varieties, null, 2)};\n`;

  writeFileSync(OUT_FILE, header + body, "utf8");
  const note = skipped > 0 ? ` (${skipped} draft${skipped === 1 ? "" : "s"} skipped)` : "";
  console.log(
    `Varieties built: ${varieties.length} variet${varieties.length === 1 ? "y" : "ies"}${note} → ${OUT_FILE}`,
  );
}

main();
