/**
 * Compiles the Blog.
 *
 * Reads every `content/blog/*.md` file (YAML front-matter + markdown body),
 * validates the front-matter, renders the body to HTML, estimates a read time,
 * and emits a single typed module at `lib/blog/generated.ts`. The app imports that
 * module directly, so the whole blog ships in the JS bundle and is fully available
 * offline — no runtime markdown parsing, no network, no CMS.
 *
 * Authoring workflow: research + write a post OUTSIDE the app, drop the `.md` into
 * `content/blog/`, then run `pnpm blog:build` (also runs automatically on `build`).
 * Set `draft: true` in the front-matter to keep a post in the repo without shipping
 * it — drafts are skipped here and never reach the bundle.
 *
 * Run with: `pnpm blog:build`
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { marked } from "marked";
import { z } from "zod";

const CONTENT_DIR = join(process.cwd(), "content", "blog");
const OUT_FILE = join(process.cwd(), "lib", "blog", "generated.ts");

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

// YAML parses an unquoted `2026-06-28` into a JS Date. Normalize either form to an
// ISO `YYYY-MM-DD` string so authors don't have to remember to quote dates.
const toIsoDate = (v: unknown): unknown => (v instanceof Date ? v.toISOString().slice(0, 10) : v);
const isoDate = (label: string) =>
  z.preprocess(toIsoDate, z.string().regex(ISO_DATE, `${label} must be YYYY-MM-DD`));

const frontMatterSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, "slug must be kebab-case (a-z, 0-9, -)"),
  title: z.string(),
  excerpt: z.string(),
  author: z.string().default("Ferment"),
  date: isoDate("date"),
  updated: isoDate("updated").optional(),
  category: z.enum(["science", "microbiology", "safety", "health", "history", "guide"]),
  tags: z.array(z.string()).default([]),
  featured: z.boolean().default(false),
  // Kept in the repo but excluded from the shipped bundle.
  draft: z.boolean().default(false),
});

marked.setOptions({ gfm: true, breaks: false });

/** ~200 wpm reading speed, floored at 1 minute. */
function readingMinutes(body: string): number {
  const words = body.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200));
}

function buildSearchText(fm: z.infer<typeof frontMatterSchema>, body: string): string {
  return [fm.title, fm.excerpt, fm.author, fm.tags.join(" "), body.replace(/[#>*`_\-[\]()]/g, " ")]
    .join(" ")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function main() {
  const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));
  if (files.length === 0) throw new Error(`No .md files found in ${CONTENT_DIR}`);

  let skipped = 0;
  const posts = files
    .map((file) => {
      const raw = readFileSync(join(CONTENT_DIR, file), "utf8");
      const { data, content } = matter(raw);
      const parsed = frontMatterSchema.safeParse(data);
      if (!parsed.success) {
        throw new Error(`Invalid front-matter in ${file}:\n${JSON.stringify(parsed.error.format(), null, 2)}`);
      }
      const fm = parsed.data;
      if (fm.draft) {
        skipped++;
        return null;
      }
      const body = content.trim();
      return {
        slug: fm.slug,
        title: fm.title,
        excerpt: fm.excerpt,
        author: fm.author,
        date: fm.date,
        updated: fm.updated,
        category: fm.category,
        tags: fm.tags,
        featured: fm.featured,
        readingMinutes: readingMinutes(body),
        bodyHtml: marked.parse(body) as string,
        searchText: buildSearchText(fm, body),
      };
    })
    .filter((p): p is NonNullable<typeof p> => p !== null)
    // Newest first — the blog reads reverse-chronological.
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.title.localeCompare(b.title)));

  if (posts.length === 0) throw new Error(`Every post in ${CONTENT_DIR} is a draft — nothing to publish.`);

  const slugs = new Set<string>();
  for (const p of posts) {
    if (slugs.has(p.slug)) throw new Error(`Duplicate blog slug: ${p.slug}`);
    slugs.add(p.slug);
  }

  const header =
    "// AUTO-GENERATED by scripts/build-blog.ts — do not edit by hand.\n" +
    "// Edit the source files in content/blog/*.md, then run `pnpm blog:build`.\n" +
    'import type { BlogPost } from "./types";\n\n';
  const body = `export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};\n`;

  writeFileSync(OUT_FILE, header + body, "utf8");
  const note = skipped > 0 ? ` (${skipped} draft${skipped === 1 ? "" : "s"} skipped)` : "";
  console.log(`Blog built: ${posts.length} post${posts.length === 1 ? "" : "s"}${note} → ${OUT_FILE}`);
}

main();
